# Generated by Django 2.1.5 on 2019-01-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('birth', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
